language: python
python:
  - "3.6"
  # - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt -r dev_requirements.txt
  - pip list
# command to run tests
script:
  - pytest -vv