language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - mkdir ~/.ego.io
  - printf '%s\n' '[oedb]' 'dialect = oedialect' 'host = oe2.iws.cs.ovgu.de' 'port = 80' 'database = oedb' 'username = ding0_test_user' 'password = password_token' > ~/.ego.io/config.ini
  - cat ~/.ego.io/config.ini
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest